### ISSUE TITLE
Question: example events

### ISSUE THREAD

**Issue by esn01** [web-dom/web-dom#2]
How does the program knows that the function callback should be called on click?
How would a program look like if there were two buttons and each had its own listener?

What about two input fields where each should be validated on lost focus.
The first one as number and the second one as date value.
???

**Comment by richardanaya** [comment]
I may not be understanding your question correctly. Are you asking how you distinguish two event sources?

```rust
#[no_mangle]
pub fn callback(_istener: EventListener, _event: Event) -> () {
    // .. get listener 1 and listener 2 from global state
    if listener == listener1 {
      window::alert(window(),"button 1 was pressed");
   } else if listener == listener2 {
      window::alert(window(),"button 2 was pressed");
   }
}

#[no_mangle]
pub fn main() -> () {
    let btn1 = document::query_selector(document(), "#button1");
    let btn2 = document::query_selector(document(), "#button2");
    let listener1 = create_event_listener();
    let listener2 = create_event_listener();
    eventtarget::add_event_listener(btn1, "click", listener1);
    eventtarget::add_event_listener(btn2, "click", listener2);
    // save listener 1 and listener 2  to global state
}
```

**Comment by esn01** [comment]
This way we have one callback function containing everything that happens inside the app.

Is there a way to do it like in js:
document.addEventListener("click", myFunction);
document.addEventListener("click", someOtherFunction); 

for example

let listener1 = create_event_listener(my_fn1);
let listener2 = create_event_listener(my_fn2);

It would be nice if we could create a web component as rust struct containing some GUI widgets and be able to register event handler to the component or to the particular contained GUI element.

**Comment by richardanaya** [comment]
In theory it is possible, but web-dom in its current state is meant to be an uber low level api, not a global state manager that holds onto closures.  I think I avoided this because it's really difficult for me to know how people create their Rust applications.

Check out my pong application how I do routing of a keydown and keyup event.

https://github.com/richardanaya/pong/

It may give you some ideas.
