### ISSUE TITLE
Unable to set canvas fill style

### ISSUE THREAD

**Issue by arthrp** [web-dom/web-dom#3]
In the current 0.1 version, set_fill_style has a strange signature:
```
pub fn set_fill_style(instance: DOMReference, value: DOMReference)
```

In the Canvas API, you'd set the style as follows:
```
ctx.fillStyle = "#000000";
```
Also in version 0.0.8 that you use for the [pong](https://github.com/richardanaya/pong) game, similar method takes a string as a second argument:
```
drawing::set_fill_style(ctx, "#0000FF");
```

As of 0.1, ```drawing``` object seems no longer available. So how do you set the style?

**Comment by richardanaya** [comment]
Sorry about that, I renamed "drawing" to "canvas" in 0.1

https://github.com/web-dom/web-dom/blob/master/examples/canvas/src/lib.rs

Updating readme now

**Comment by richardanaya** [comment]
Actually, there seems to be an issue with fill_style too, fixing this asap.

**Comment by richardanaya** [comment]
https://richardanaya.github.io/pong/
https://github.com/richardanaya/pong/blob/master/src/game.rs

fixed, sorry about that confusion

**Comment by arthrp** [comment]
Thanks!
